@props(['vatRates','discountTypes'])
<section class="card"><div class="flex items-center justify-between gap-3"><div><h2 class="text-lg font-bold">3. Položky</h2><p class="mt-1 text-sm text-slate-600">Jednotková cena je bez DPH.</p></div><button class="button-secondary" type="button" @click="addItem">Přidat položku</button></div>
    @error('items')<p class="field-error" role="alert">{{ $message }}</p>@enderror
    <div class="mt-5 space-y-4">
        <template x-for="(item,index) in items" :key="index"><fieldset class="rounded-xl border border-slate-200 p-4"><legend class="px-2 font-semibold" x-text="`Položka ${index+1}`"></legend><input type="hidden" :name="`items[${index}][position]`" :value="index+1"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <div class="md:col-span-2"><label :for="`item-${index}-description`">Popis *</label><input :id="`item-${index}-description`" :name="`items[${index}][description]`" x-model="item.description" maxlength="255" required><p class="field-error" x-show="fieldError(index,'description')" x-text="fieldError(index,'description')"></p></div>
            <div><label :for="`item-${index}-quantity`">Množství *</label><input :id="`item-${index}-quantity`" :name="`items[${index}][quantity]`" x-model="item.quantity" inputmode="decimal" required><p class="field-error" x-show="fieldError(index,'quantity')" x-text="fieldError(index,'quantity')"></p></div>
            <div><label :for="`item-${index}-unit`">Jednotka</label><input :id="`item-${index}-unit`" :name="`items[${index}][unit]`" x-model="item.unit" maxlength="32"></div>
            <div><label :for="`item-${index}-price`">Cena bez DPH *</label><input :id="`item-${index}-price`" :name="`items[${index}][unit_price]`" x-model="item.unit_price" inputmode="decimal" required><p class="field-error" x-show="fieldError(index,'unit_price')" x-text="fieldError(index,'unit_price')"></p></div>
            <div><label :for="`item-${index}-discount-type`">Sleva</label><select :id="`item-${index}-discount-type`" :name="`items[${index}][discount_type]`" x-model="item.discount_type">@foreach($discountTypes as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
            <div><label :for="`item-${index}-discount-value`">Hodnota slevy</label><input :id="`item-${index}-discount-value`" :name="`items[${index}][discount_value]`" x-model="item.discount_value" inputmode="decimal"><p class="field-error" x-show="fieldError(index,'discount_value')" x-text="fieldError(index,'discount_value')"></p></div>
            <div><label :for="`item-${index}-vat`">Sazba DPH *</label><select :id="`item-${index}-vat`" :name="`items[${index}][vat_rate_uuid]`" x-model="item.vat_rate_uuid" required><option value="">Vyberte sazbu</option>@foreach($vatRates as $rate)<option value="{{ $rate->uuid }}">{{ $rate->name }}@if($rate->percentage !== null) · {{ \App\Domain\Invoices\InvoiceDecimal::format($rate->percentage) }} % @endif</option>@endforeach</select><p class="field-error" x-show="fieldError(index,'vat_rate_uuid')" x-text="fieldError(index,'vat_rate_uuid')"></p></div>
        </div><div class="mt-4 flex flex-wrap gap-2"><button type="button" class="button-secondary" @click="move(index,-1)" :disabled="index===0" :aria-label="`Posunout položku ${index+1} nahoru`">Nahoru</button><button type="button" class="button-secondary" @click="move(index,1)" :disabled="index===items.length-1" :aria-label="`Posunout položku ${index+1} dolů`">Dolů</button><button type="button" class="button-secondary text-red-700" @click="removeItem(index)" :disabled="items.length===1" :aria-label="`Odebrat položku ${index+1}`">Odebrat</button></div></fieldset></template>
    </div>
    <x-invoices.noscript-item :vat-rates="$vatRates" :discount-types="$discountTypes" />
</section>
