<x-layouts.app>
    <x-slot:title>{{ $rate->name }}</x-slot:title>
    <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-bold">{{ $rate->name }}</h1><p class="mt-1 text-sm text-slate-600">Kód {{ $rate->code }}</p></div><a class="button-secondary" href="{{ route('vat-rates.index') }}">Zpět na seznam</a></div>
    <div class="mt-5">@include('business.vat-rates._warning')</div>
    <div class="mt-5 grid gap-5 lg:grid-cols-2">
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-semibold">Konfigurace</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><dt class="text-slate-500">Daňový režim</dt><dd>{{ $rate->tax_type->label() }}</dd><dt class="text-slate-500">Sazba</dt><dd>{{ $rate->percentage !== null ? $rate->percentage.' %' : 'Bez výpočtu sazby' }}</dd><dt class="text-slate-500">Platnost</dt><dd>{{ $rate->valid_from->format('d. m. Y') }} – {{ $rate->valid_to?->format('d. m. Y') ?? 'bez konce' }}</dd><dt class="text-slate-500">Stav</dt><dd>@if($rate->isArchived()) Archivovaná @elseif($rate->is_active) Aktivní @else Neaktivní @endif</dd><dt class="text-slate-500">Výchozí</dt><dd>{{ $rate->defaultAssignment ? 'Ano, pro prodej' : 'Ne' }}</dd><dt class="text-slate-500">Pořadí</dt><dd>{{ $rate->sort_order }}</dd></dl><div class="mt-5">@include('business.vat-rates._actions')</div></section>
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-semibold">Historie změn</h2><div class="mt-4 space-y-3">@forelse($auditLogs as $log)<a class="block rounded-lg border border-slate-200 p-3 hover:bg-slate-50" href="{{ route('business-audit.show', $log->uuid) }}"><span class="font-medium">{{ $log->event->label() }}</span><span class="block text-xs text-slate-500">{{ $log->occurred_at->format('d. m. Y H:i:s') }} · {{ $log->actor_name ?? 'Systém' }}</span></a>@empty<p class="text-sm text-slate-500">Zatím bez auditních událostí.</p>@endforelse</div></section>
    </div>
</x-layouts.app>
