<x-layouts.app :title="$audit->event->label()">
    <div class="mb-6"><p class="text-sm font-medium text-blue-700">Audit změn</p><h1 class="mt-1 text-2xl font-bold">{{ $audit->event->label() }}</h1><p class="mt-2 text-sm text-slate-600">Auditní záznam je neměnný a pouze ke čtení.</p></div>
    <div class="grid gap-6 xl:grid-cols-2">
        <section class="card"><h2 class="text-lg font-bold">Událost</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-slate-500">Čas</dt><dd>{{ $audit->occurred_at->format('j. n. Y H:i:s.u') }}</dd></div><div><dt class="text-slate-500">Typ entity</dt><dd>{{ $audit->auditable_type->label() }}</dd></div><div><dt class="text-slate-500">UUID entity</dt><dd class="break-all font-mono">{{ $audit->auditable_uuid ?? '—' }}</dd></div><div><dt class="text-slate-500">Uživatel</dt><dd>{{ $audit->actor_name ?? 'Systém' }}@if($audit->actor_email)<span class="block text-slate-500">{{ $audit->actor_email }}</span>@endif</dd></div></dl></section>
        <section class="card"><h2 class="text-lg font-bold">Technický kontext</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-slate-500">Request ID</dt><dd class="break-all font-mono">{{ $audit->request_id ?? '—' }}</dd></div><div><dt class="text-slate-500">IP adresa</dt><dd>{{ $audit->ip_address ?? 'Není dostupná' }}</dd></div><div><dt class="text-slate-500">User-Agent</dt><dd class="break-words">{{ $audit->user_agent ? \Illuminate\Support\Str::limit($audit->user_agent, 180) : 'Není dostupný' }}</dd></div>@if($audit->subject_type)<div><dt class="text-slate-500">Související entita</dt><dd>{{ $audit->subject_type->label() }} · <span class="font-mono">{{ $audit->subject_uuid }}</span></dd></div>@endif</dl></section>
    </div>
    @foreach(['changed_fields'=>'Změněná pole','old_values'=>'Původní bezpečné hodnoty','new_values'=>'Nové bezpečné hodnoty','metadata'=>'Metadata'] as $field=>$label)
        <section class="card mt-6"><h2 class="text-lg font-bold">{{ $label }}</h2>@if(empty($audit->{$field}))<p class="mt-3 text-sm text-slate-500">Žádné hodnoty.</p>@else<dl class="mt-4 space-y-2 text-sm">@foreach($audit->{$field} as $key=>$value)<div class="grid gap-1 sm:grid-cols-3"><dt class="font-mono text-slate-500">{{ is_int($key) ? $value : $key }}</dt>@if(!is_int($key))<dd class="break-all sm:col-span-2">{{ is_bool($value) ? ($value ? 'Ano' : 'Ne') : (is_array($value) ? json_encode($value, JSON_UNESCAPED_UNICODE) : $value) }}</dd>@endif</div>@endforeach</dl>@endif</section>
    @endforeach
    <div class="mt-6"><a href="{{ route('business-audit.index') }}" class="button-secondary">Zpět na audit</a></div>
</x-layouts.app>
